/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as ArchivedRouteImport } from './routes/archived'
import { Route as CalendarRouteImport } from './routes/calendar'
import { Route as ComposeRouteImport } from './routes/compose'
import { Route as ContactsRouteImport } from './routes/contacts'
import { Route as DraftsRouteImport } from './routes/drafts'
import { Route as FoldersRouteImport } from './routes/folders'
import { Route as InboxRouteImport } from './routes/inbox'
import { Route as LoginRouteImport } from './routes/login'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as SentRouteImport } from './routes/sent'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as SetupRouteImport } from './routes/setup'
import { Route as SnoozedRouteImport } from './routes/snoozed'
import { Route as SpamRouteImport } from './routes/spam'
import { Route as StarredRouteImport } from './routes/starred'
import { Route as TrashRouteImport } from './routes/trash'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as AdminBackupsRouteImport } from './routes/admin/backups'
import { Route as AdminDomainsRouteImport } from './routes/admin/domains'
import { Route as AdminMailboxesRouteImport } from './routes/admin/mailboxes'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const ArchivedRoute = ArchivedRouteImport.update({
  id: '/archived',
  path: '/archived',
  getParentRoute: () => rootRouteImport,
} as any)
const CalendarRoute = CalendarRouteImport.update({
  id: '/calendar',
  path: '/calendar',
  getParentRoute: () => rootRouteImport,
} as any)
const ComposeRoute = ComposeRouteImport.update({
  id: '/compose',
  path: '/compose',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactsRoute = ContactsRouteImport.update({
  id: '/contacts',
  path: '/contacts',
  getParentRoute: () => rootRouteImport,
} as any)
const DraftsRoute = DraftsRouteImport.update({
  id: '/drafts',
  path: '/drafts',
  getParentRoute: () => rootRouteImport,
} as any)
const FoldersRoute = FoldersRouteImport.update({
  id: '/folders',
  path: '/folders',
  getParentRoute: () => rootRouteImport,
} as any)
const InboxRoute = InboxRouteImport.update({
  id: '/inbox',
  path: '/inbox',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const SentRoute = SentRouteImport.update({
  id: '/sent',
  path: '/sent',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const SetupRoute = SetupRouteImport.update({
  id: '/setup',
  path: '/setup',
  getParentRoute: () => rootRouteImport,
} as any)
const SnoozedRoute = SnoozedRouteImport.update({
  id: '/snoozed',
  path: '/snoozed',
  getParentRoute: () => rootRouteImport,
} as any)
const SpamRoute = SpamRouteImport.update({
  id: '/spam',
  path: '/spam',
  getParentRoute: () => rootRouteImport,
} as any)
const StarredRoute = StarredRouteImport.update({
  id: '/starred',
  path: '/starred',
  getParentRoute: () => rootRouteImport,
} as any)
const TrashRoute = TrashRouteImport.update({
  id: '/trash',
  path: '/trash',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminBackupsRoute = AdminBackupsRouteImport.update({
  id: '/backups',
  path: '/backups',
  getParentRoute: () => AdminRoute,
} as any)
const AdminDomainsRoute = AdminDomainsRouteImport.update({
  id: '/domains',
  path: '/domains',
  getParentRoute: () => AdminRoute,
} as any)
const AdminMailboxesRoute = AdminMailboxesRouteImport.update({
  id: '/mailboxes',
  path: '/mailboxes',
  getParentRoute: () => AdminRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/archived': typeof ArchivedRoute
  '/calendar': typeof CalendarRoute
  '/compose': typeof ComposeRoute
  '/contacts': typeof ContactsRoute
  '/drafts': typeof DraftsRoute
  '/folders': typeof FoldersRoute
  '/inbox': typeof InboxRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/sent': typeof SentRoute
  '/settings': typeof SettingsRoute
  '/setup': typeof SetupRoute
  '/snoozed': typeof SnoozedRoute
  '/spam': typeof SpamRoute
  '/starred': typeof StarredRoute
  '/trash': typeof TrashRoute
  '/admin/backups': typeof AdminBackupsRoute
  '/admin/domains': typeof AdminDomainsRoute
  '/admin/mailboxes': typeof AdminMailboxesRoute
  '/admin/': typeof AdminIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/archived': typeof ArchivedRoute
  '/calendar': typeof CalendarRoute
  '/compose': typeof ComposeRoute
  '/contacts': typeof ContactsRoute
  '/drafts': typeof DraftsRoute
  '/folders': typeof FoldersRoute
  '/inbox': typeof InboxRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/sent': typeof SentRoute
  '/settings': typeof SettingsRoute
  '/setup': typeof SetupRoute
  '/snoozed': typeof SnoozedRoute
  '/spam': typeof SpamRoute
  '/starred': typeof StarredRoute
  '/trash': typeof TrashRoute
  '/admin/backups': typeof AdminBackupsRoute
  '/admin/domains': typeof AdminDomainsRoute
  '/admin/mailboxes': typeof AdminMailboxesRoute
  '/admin': typeof AdminIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/archived': typeof ArchivedRoute
  '/calendar': typeof CalendarRoute
  '/compose': typeof ComposeRoute
  '/contacts': typeof ContactsRoute
  '/drafts': typeof DraftsRoute
  '/folders': typeof FoldersRoute
  '/inbox': typeof InboxRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/sent': typeof SentRoute
  '/settings': typeof SettingsRoute
  '/setup': typeof SetupRoute
  '/snoozed': typeof SnoozedRoute
  '/spam': typeof SpamRoute
  '/starred': typeof StarredRoute
  '/trash': typeof TrashRoute
  '/admin/backups': typeof AdminBackupsRoute
  '/admin/domains': typeof AdminDomainsRoute
  '/admin/mailboxes': typeof AdminMailboxesRoute
  '/admin/': typeof AdminIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/archived'
    | '/calendar'
    | '/compose'
    | '/contacts'
    | '/drafts'
    | '/folders'
    | '/inbox'
    | '/login'
    | '/register'
    | '/sent'
    | '/settings'
    | '/setup'
    | '/snoozed'
    | '/spam'
    | '/starred'
    | '/trash'
    | '/admin/backups'
    | '/admin/domains'
    | '/admin/mailboxes'
    | '/admin/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/archived'
    | '/calendar'
    | '/compose'
    | '/contacts'
    | '/drafts'
    | '/folders'
    | '/inbox'
    | '/login'
    | '/register'
    | '/sent'
    | '/settings'
    | '/setup'
    | '/snoozed'
    | '/spam'
    | '/starred'
    | '/trash'
    | '/admin/backups'
    | '/admin/domains'
    | '/admin/mailboxes'
    | '/admin'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/archived'
    | '/calendar'
    | '/compose'
    | '/contacts'
    | '/drafts'
    | '/folders'
    | '/inbox'
    | '/login'
    | '/register'
    | '/sent'
    | '/settings'
    | '/setup'
    | '/snoozed'
    | '/spam'
    | '/starred'
    | '/trash'
    | '/admin/backups'
    | '/admin/domains'
    | '/admin/mailboxes'
    | '/admin/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  ArchivedRoute: typeof ArchivedRoute
  CalendarRoute: typeof CalendarRoute
  ComposeRoute: typeof ComposeRoute
  ContactsRoute: typeof ContactsRoute
  DraftsRoute: typeof DraftsRoute
  FoldersRoute: typeof FoldersRoute
  InboxRoute: typeof InboxRoute
  LoginRoute: typeof LoginRoute
  RegisterRoute: typeof RegisterRoute
  SentRoute: typeof SentRoute
  SettingsRoute: typeof SettingsRoute
  SetupRoute: typeof SetupRoute
  SnoozedRoute: typeof SnoozedRoute
  SpamRoute: typeof SpamRoute
  StarredRoute: typeof StarredRoute
  TrashRoute: typeof TrashRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/archived': {
      id: '/archived'
      path: '/archived'
      fullPath: '/archived'
      preLoaderRoute: typeof ArchivedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/calendar': {
      id: '/calendar'
      path: '/calendar'
      fullPath: '/calendar'
      preLoaderRoute: typeof CalendarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/compose': {
      id: '/compose'
      path: '/compose'
      fullPath: '/compose'
      preLoaderRoute: typeof ComposeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contacts': {
      id: '/contacts'
      path: '/contacts'
      fullPath: '/contacts'
      preLoaderRoute: typeof ContactsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/drafts': {
      id: '/drafts'
      path: '/drafts'
      fullPath: '/drafts'
      preLoaderRoute: typeof DraftsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/folders': {
      id: '/folders'
      path: '/folders'
      fullPath: '/folders'
      preLoaderRoute: typeof FoldersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inbox': {
      id: '/inbox'
      path: '/inbox'
      fullPath: '/inbox'
      preLoaderRoute: typeof InboxRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sent': {
      id: '/sent'
      path: '/sent'
      fullPath: '/sent'
      preLoaderRoute: typeof SentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/setup': {
      id: '/setup'
      path: '/setup'
      fullPath: '/setup'
      preLoaderRoute: typeof SetupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/snoozed': {
      id: '/snoozed'
      path: '/snoozed'
      fullPath: '/snoozed'
      preLoaderRoute: typeof SnoozedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/spam': {
      id: '/spam'
      path: '/spam'
      fullPath: '/spam'
      preLoaderRoute: typeof SpamRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/starred': {
      id: '/starred'
      path: '/starred'
      fullPath: '/starred'
      preLoaderRoute: typeof StarredRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/trash': {
      id: '/trash'
      path: '/trash'
      fullPath: '/trash'
      preLoaderRoute: typeof TrashRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/backups': {
      id: '/admin/backups'
      path: '/backups'
      fullPath: '/admin/backups'
      preLoaderRoute: typeof AdminBackupsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/domains': {
      id: '/admin/domains'
      path: '/domains'
      fullPath: '/admin/domains'
      preLoaderRoute: typeof AdminDomainsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/mailboxes': {
      id: '/admin/mailboxes'
      path: '/mailboxes'
      fullPath: '/admin/mailboxes'
      preLoaderRoute: typeof AdminMailboxesRouteImport
      parentRoute: typeof AdminRoute
    }
  }
}

interface AdminRouteChildren {
  AdminBackupsRoute: typeof AdminBackupsRoute
  AdminDomainsRoute: typeof AdminDomainsRoute
  AdminMailboxesRoute: typeof AdminMailboxesRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminBackupsRoute: AdminBackupsRoute,
  AdminDomainsRoute: AdminDomainsRoute,
  AdminMailboxesRoute: AdminMailboxesRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  ArchivedRoute: ArchivedRoute,
  CalendarRoute: CalendarRoute,
  ComposeRoute: ComposeRoute,
  ContactsRoute: ContactsRoute,
  DraftsRoute: DraftsRoute,
  FoldersRoute: FoldersRoute,
  InboxRoute: InboxRoute,
  LoginRoute: LoginRoute,
  RegisterRoute: RegisterRoute,
  SentRoute: SentRoute,
  SettingsRoute: SettingsRoute,
  SetupRoute: SetupRoute,
  SnoozedRoute: SnoozedRoute,
  SpamRoute: SpamRoute,
  StarredRoute: StarredRoute,
  TrashRoute: TrashRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
